#!/usr/bin/env -S sudo bash
file="$1"
file_basename="$(basename "$file")"
file_dirname="$(dirname "$file")"
dir="$(dirname "$file")"
device="$(df --output=source "$dir" | grep '/')"
mountpoint="$(df --output=target "$dir" | grep '/')"

possible_backups="$file_dirname"/."$file_basename".s??
backup_format='vim swapfile'
for possible_backup in $possible_backups
do
	if [ -e "$possible_backup" ]
	then
		echo File found backed up at "$possible_backup" as a "$backup_format"
	else
		false
	fi
done && exit 0

# note: we could start imaging the drive to sia skynet or something, even
# though it is mounted.
echo "Scanning for processes with open handles on $device ..."
for opened_handle in /proc/*/fd/*
do
	echo -n "$opened_handle "; readlink "$opened_handle"
done | grep -F "$mountpoint"
